// Rules consumed by formula selection and Director generation. These are stored
// settings leaves, not character keywords or a command to trigger a new round.
const integer = minimum => ({ type: 'integer', minimum, maximum: Number.MAX_SAFE_INTEGER });
const count = { type: 'integer', minimum: 1, maximum: 200 };

export const formulaRuleDefinitions = {
    recentMessageCount: { domain: 'scoring', schema: count, dependencies: ['mode'], idle: true, source: 'ui/sections/formula.js', description: '公式评分查看的最近消息条数；本工具支持1..200，原界面与运行时没有200的强制上限。只影响后续公式选人，不改变聊天历史。' },
    consecutivePenalty: { domain: 'scoring', schema: integer(0), dependencies: ['mode'], idle: true, source: 'ui/sections/formula.js', description: '同一角色连续发言时每条消息扣除的分数；0关闭这项扣分。只影响后续公式选人。' },
    triggerEnabled: { domain: 'scoring', schema: { type: 'boolean' }, dependencies: ['mode'], idle: true, source: 'ui/sections/formula.js', description: '控制公式选人的关键词触发。关键词来自角色描述、性格和场景，并非此配置里的独立列表；不编辑角色资料。' },
    triggerScore: { domain: 'scoring', schema: integer(0), dependencies: ['mode', 'triggerEnabled'], idle: true, source: 'ui/sections/formula.js', description: '公式选人中角色关键词命中时的加分；触发开关关闭时，数值保留但不会加分。' },
    initiativeEnabled: { domain: 'scoring', schema: { type: 'boolean' }, dependencies: ['mode'], idle: true, source: 'ui/sections/formula.js', description: '控制公式选人的主动性随机加分；不设置某个角色本轮实际获得的分数。' },
    initiativeBaseScore: { domain: 'scoring', schema: integer(0), dependencies: ['mode', 'initiativeEnabled'], idle: true, source: 'ui/sections/formula.js', description: '公式选人的主动性随机加分上界，运行时为 random()*baseScore；开关关闭时数值保留但不生效。' },
};

export const directorRuleDefinitions = {
    llmContextDepth: { domain: 'director', schema: count, idle: true, source: 'ui/sections/director.js', description: '最近消息条数；本工具支持1..200。导演、记忆、NPC、强制发言等流程共享此值，会影响后续调用的上下文开销。' },
    llmScriptEnabled: { domain: 'director', schema: { type: 'boolean' }, dependencies: ['mode'], idle: true, source: 'ui/sections/director.js', description: 'LLM导演模式的舞台指导开关；启用后导演输出可包含角色 scripts，并在后续角色生成时注入指导文本。不是脚本执行器，不运行 JavaScript；不修改已保存的导演历史。' },
    llmScriptPrompt: { domain: 'director', schema: { type: 'string', maxLength: 4000 }, dependencies: ['mode', 'llmScriptEnabled'], idle: true, source: 'ui/sections/director.js', description: '导演剧本风格要求原文。仅在后续 LLM 导演构造计划且舞台指导开启时，作为 Script theme / requirements 文本附加到导演 Prompt；空串不附加此要求，不会立即生成剧本或修改已有导演历史。最多 4000 字符。' },
    llmScriptWrapper: { domain: 'director', schema: { type: 'string', maxLength: 4000 }, dependencies: ['mode', 'llmScriptEnabled'], idle: true, source: 'ui/sections/director.js', description: '后续角色生成时的导演剧本注入包装文本。运行时先将每个 {{script}} 替换为该角色剧本，再由通用 Prompt 渲染器处理其他已注册 Provider；因此自定义占位符可能读取聊天资料、触发用户 Provider，并发送至配置的模型。缺少 {{script}} 将不注入剧本文本；空串实际退回纯 {{script}}，并非出厂包装模板。只影响后续注入，不改历史；最多 4000 字符。' },
    llmJsonSchema: { domain: 'director', schema: { type: 'string', maxLength: 4000 }, dependencies: ['mode', 'forceSpeakMode', 'llmScriptEnabled', 'storyBlueprintEnabled'], idle: true, source: 'ui/sections/director.js', description: 'Director 与 LLM 强制发言共用的 JSON 输出格式提示原文，不是模型原生 JSON Schema，也不用于严格校验回复。运行时按开关替换 {{scriptField}} 与 {{storyBlueprintDoneField}}，并移除自引用 {{llmJsonSchema}}；若主 Prompt 未包含 {{llmJsonSchema}}，会在渲染后追加本字段文本。空串运行时不提供格式提示，经典界面的“默认”按钮则写入实际内置文本。至少说明 speakers 数组，否则导演无法可靠选人；修改只影响之后的模型请求。最多 4000 字符。' },
    llmScriptPosition: { domain: 'director', schema: { type: 'integer', enum: [0, 1] }, dependencies: ['mode', 'llmScriptEnabled'], idle: true, source: 'ui/sections/director.js', description: '舞台指导注入位置：0 为 Prompt 开头，1 为对话附近；后者对生成影响更直接。仅在 LLM 模式且舞台指导开启时用于后续角色生成。' },
    llmScriptContinuity: { domain: 'director', schema: { type: 'boolean' }, dependencies: ['mode', 'llmHistoryEnabled'], idle: true, source: 'ui/sections/continuity.js', description: 'LLM导演模式下将当前聊天已保存的导演决策用于后续轮次连续性；需要导演历史记录开启且存在历史。可能增加发送给模型的上下文；不立即重跑旧轮次。' },
    llmScriptContinuityMode: { domain: 'director', schema: { type: 'string', enum: ['last', 'history'] }, dependencies: ['mode', 'llmHistoryEnabled', 'llmScriptContinuity'], idle: true, source: 'ui/sections/continuity.js', description: 'last 仅注入上一份导演计划；history 注入多份历史计划，受 llmScriptContinuityCount 控制。只影响后续 LLM 导演请求。' },
    llmScriptContinuityCount: { domain: 'director', schema: { type: 'integer', minimum: 0, maximum: 100 }, dependencies: ['mode', 'llmHistoryEnabled', 'llmScriptContinuity', 'llmScriptContinuityMode'], idle: true, source: 'ui/sections/continuity.js', description: 'history 模式注入的最近导演计划份数；本工具支持 0..100，0 在现有运行时表示全部已保存历史，并非关闭。可能显著增加上下文与调用费用。' },
    llmScriptContinuityWrapper: { domain: 'director', schema: { type: 'string', maxLength: 4000 }, dependencies: ['mode', 'forceSpeakMode', 'llmHistoryEnabled', 'llmScriptContinuity', 'llmScriptContinuityMode', 'llmScriptContinuityCount', 'llmPrompt'], idle: true, source: 'ui/sections/continuity.js', description: 'last 模式下包装当前聊天上一份已保存导演计划的文本。运行时只把首个 {{previousPlan}} 替换为该计划的 JSON；空串退回纯 JSON 包装，不是出厂说明文字。默认导演 Prompt 显式使用历史 Provider；自定义主 Prompt 若无历史占位符，Director 才自动前置此模板。Force Speak 仅在主 Prompt 显式引用历史 Provider 时使用。需历史和连续性开启且有已保存计划；只影响之后的模型请求，可能发送聊天历史，最多 4000 字符。' },
    llmScriptContinuityHistoryWrapper: { domain: 'director', schema: { type: 'string', maxLength: 4000 }, dependencies: ['mode', 'forceSpeakMode', 'llmHistoryEnabled', 'llmScriptContinuity', 'llmScriptContinuityMode', 'llmScriptContinuityCount', 'llmPrompt'], idle: true, source: 'ui/sections/continuity.js', description: 'history 模式下包装当前聊天多份已保存导演计划的文本。运行时只把首个 {{previousPlans}} 替换为 JSON 数组；空串退回纯 JSON 包装，不是出厂说明文字。历史轮数 0 表示全部，不是关闭；默认导演 Prompt 显式使用历史 Provider，自定义主 Prompt 无历史占位符时 Director 才自动前置。Force Speak 仅经显式 Provider 使用。需历史和连续性开启且有计划；可能明显增加模型上下文费用，最多 4000 字符。' },
    forceSpeakMode: { domain: 'director', schema: { type: 'string', enum: ['native', 'block', 'llm'] }, idle: true, source: 'ui/sections/forceSpeak.js', description: '强制发言处理：native 原生放行，block 直接截停，llm 交给独立强制发言模型接管。llm 可能增加模型调用且依赖其连接；不立即触发发言。' },
    forceSpeakPrompt: { domain: 'director', schema: { type: 'string', maxLength: 4000 }, dependencies: ['forceSpeakMode', 'lang'], idle: true, source: 'ui/sections/forceSpeak.js', description: 'LLM 强制发言时追加到导演 Prompt 尾部的指导原文；{charName} 会替换为指定角色名称，空串使用当前界面语言对应的内置指令。此追加文本不会再次经过通用 Provider 渲染；不包含 {charName} 时可能失去明确的角色约束。仅影响后续 LLM 强制发言，不立即触发生成；最多 4000 字符。' },
    templateMaxPasses: { domain: 'director', schema: { type: 'integer', minimum: 1, maximum: 10 }, dependencies: ['templateRecursive'], idle: true, source: 'ui/sections/director.js', description: '递归模板最多渲染轮数；本工具保守支持 1..10，旧 UI 和渲染器上限更宽。1 相当于只做首轮解析；影响后续导演、强制发言、蓝图等 Prompt。' },
    templateRecursive: { domain: 'director', schema: { type: 'boolean' }, idle: true, source: 'ui/sections/director.js', description: '是否继续解析 Provider 输出中残留的占位符；关闭时只解析首轮。影响后续多个功能的 Prompt，开启可能增加渲染工作量，但同次渲染复用 Provider 结果。' },
    templateDebugPlaceholders: { domain: 'director', schema: { type: 'boolean' }, idle: true, source: 'ui/sections/director.js', description: '调试模式：保留无法解析的占位符文本以便排查；可能使原样占位符进入模型 Prompt。影响后续多个功能的渲染，不改变 Provider 注册。' },
    llmHistoryEnabled: { domain: 'director', schema: { type: 'boolean' }, idle: true, source: 'ui/sections/director.js', description: '控制后续导演及强制发言决策是否写入当前聊天的导演历史；本设置写入不主动清空已有历史，但聊天消息删除后的常规历史清理仍会进行。导演连续性功能可能读取已保存的历史。影响所有聊天的后续决策。开关值不证明已产生决策、已写入历史或持久化成功。' },
    llmWorldInfoEnabled: { domain: 'director', schema: { type: 'boolean' }, idle: true, source: 'ui/sections/worldinfo.js', description: '控制后续导演及强制发言流程是否查询当前激活的 ST 世界书并将相关内容注入模型上下文；可能增加上下文开销并向所配置模型发送世界书正文。关闭不修改世界书或已有聊天记录，不控制 worldBooks/worldBookImportance 等独立世界书 Provider；不能据此说所有世界书读取或注入都关闭。开启也不证明实际有激活条目或已完成注入。' },
    llmWorldInfoWrapper: { domain: 'director', schema: { type: 'string', maxLength: 4000 }, dependencies: ['llmWorldInfoEnabled', 'llmPrompt'], idle: true, source: 'ui/sections/worldinfo.js', description: '全局世界书包装模板，影响后续使用 {{worldInfo}} Provider 的 Prompt，以及 Director/LLM 强制发言在主 Prompt 未显式包含该占位符时的自动前置。运行时仅替换首个 {{worldInfo}}；非空模板缺少它将丢失世界书正文，重复出现只替换首个。空串退回纯世界书正文，不恢复出厂包装。需开启世界书注入并有实际激活条目才会附加内容；预览不读取世界书正文。其他 Provider 占位符在显式 Provider 与自动前置路径的渲染结果可能不同。最多 4000 字符，影响所有聊天并可能向模型发送世界书正文。' },
    llmRespectOrder: { domain: 'director', schema: { type: 'boolean' }, dependencies: ['mode'], idle: true, source: 'ui/sections/director.js', description: 'LLM模式下按导演返回顺序逐人生成，接管SillyTavern激活循环；只影响后续轮次。' },
    llmCharDescMode: { domain: 'director', schema: { type: 'string', enum: ['full', 'slice'] }, idle: true, source: 'ui/sections/director.js', description: '角色描述注入方式：full为完整描述，slice按llmCharDescLength截断。启用角色档案时，角色描述可能被档案文本替代。' },
    llmCharDescLength: { domain: 'director', schema: { type: 'integer', minimum: 1, maximum: 4000 }, dependencies: ['llmCharDescMode'], idle: true, source: 'ui/sections/director.js', description: 'slice模式下每个角色描述的截断长度，单位为JavaScript字符串字符；本工具支持1..4000。full模式下此值保留但不用于截断。' },
};
