import { CONTEXT_DEFAULTS, MAX_MANUAL_INPUT_TOKENS, SUMMARY_TIME_RANGE } from '../context/policy.js';
import { formatBudget } from './budget-view.js';
import { permissionDisplayTitle } from './catalog-labels.js';
import { createFormFeedback } from './form-feedback.js';
import { bindAutoSave } from './auto-save.js';

/** View only. Summary text is plain reference data; no operation comes from model output. */
export function createContextView({ doc, settings, parent, controller, act, lang }) {
    const t = (zh, en) => lang === 'en' ? en : zh;
    const permissionTitle = id => permissionDisplayTitle(id, lang);
    const node = (tag, text, owner) => { const el = doc.createElement(tag); el.textContent = text; owner.append(el); return el; };
    const button = (text, owner) => { const el = node('button', text, owner); el.type = 'button'; el.className = 'menu_button'; return el; };
    const field = (text, type, owner) => { const label = node('label', text, owner), el = node('input', '', label); el.type = type; el.className = type === 'checkbox' ? '' : 'text_pole'; return el; };
    const config = node('details', '', settings); node('summary', t('上下文预算', 'Context budget'), config);
    config.open = true;
    config.className = 'gd-muyu-settings-card';
    node('small', t('自动保存：开关与选择立即保存，数字完成编辑后保存；下一轮生效。', 'Auto-save switches and selections immediately, numbers after editing; effective next task.'), config);
    const historyGroup = node('div', '', config); historyGroup.className = 'gd-muyu-settings-group';
    node('h4', t('携带已有对话', 'Conversation history'), historyGroup);
    const historyLabel = node('label', t('已有对话外发', 'Sending existing conversation history'), historyGroup);
    const historyPolicy = node('select', '', historyLabel); historyPolicy.className = 'text_pole';
    for (const [value, label] of [['auto', t('自动允许（默认）', 'Allow automatically (default)')], ['ask', t('逐次审批（授权失效时确认）', 'Ask when authorization expires')]]) { const option = node('option', label, historyPolicy); option.value = value; }
    node('small', t('自动允许会将已有问答及其中引用的资料发送到当前配置的模型服务，包括更换连接后。仅允许携带已有对话，不授权重新读取酒馆资料、修改配置或执行代码；仍可选择本次不携带旧历史。', 'Automatic mode sends existing conversation turns and quoted data to the configured model service, including after changing connections. It grants no fresh host reads, writes or code execution. You can still omit history for a send.'), config);
    node('p', t('输入预算控制每次发给模型的上下文总量。默认适配 1M 上下文模型；使用较小模型时请降低预算。增大预算可能增加费用。', 'Input budget limits the context sent to the model. Defaults target 1M-context models; lower the budget for smaller models. Larger budgets may cost more.'), config);
    const budgetHelp = node('details', '', config); node('summary', t('预算估算与旧设置说明', 'Budget estimates and existing settings'), budgetHelp);
    node('small', t('默认输入预算为 900000 估算 Token，留出输出与估算余量；历史另预留 10% 给问题、指令和工具。估算不是模型实际窗口。旧版默认小预算自动升级，自定义组合及重新保存的手动预算保留。', 'Default input budget: 900000 estimated tokens, leaving room for output and estimation error. History reserves another 10% for the question, instructions and tools. Estimates are not the model window. Legacy defaults upgrade; custom combinations and explicitly re-saved budgets remain.'), budgetHelp);
    const autoBudget = field(t('仅按请求体保护（8 MiB；不限制估算 Token）', 'Request-size protection only (8 MiB; no token cap)'), 'checkbox', config);
    const tokens = field(t('手动输入预算（估算 Token）', 'Manual input budget (estimated tokens)'), 'number', config); tokens.min = 4096; tokens.max = MAX_MANUAL_INPUT_TOKENS; tokens.step = 1;
    autoBudget.onchange = () => { tokens.disabled = autoBudget.checked; };
    const auto = field(t('发送时自动整理较早历史（额外模型调用，默认关闭）', 'Auto-summarize on send (extra model call, off by default)'), 'checkbox', config);
    node('small', t('历史较长时按需整理；会额外调用模型，原始对话仍保留。设置自动保存，下一轮生效。', 'Summarize long histories when needed. Uses an extra model call and retains originals. Settings save automatically for the next task.'), config);
    const compression = node('details', '', config); compression.className = 'gd-muyu-settings-advanced';
    node('summary', t('历史整理与摘要预算', 'History summarization and budget'), compression);
    node('p', t('输入预算决定能带多少资料；摘要预算决定整理后的长度；单次输出上限决定每次回答最多生成多少。', 'Input budget limits the context sent to the model. Summary budget limits the summary length. Per-call output limits how much each response can generate.'), compression);
    const turns = field(t('整理时保留近期问答的参考值', 'Recent-turn reference for summarization'), 'number', compression); turns.min = 1; turns.max = 24; turns.step = 1;
    node('small', t('长对话按输入预算的 10% 保留近期原文，按完整问答向前扩展，不固定两轮。全部原文已能放入该额度的短对话，才使用上方轮数参考值；至少留一轮作为整理候选。仅请求体保护模式按 8 MiB 上限计算。保留额度不足时可整轮摘要，不截断问答；原始记录不删除。', 'Long conversations retain a contiguous recent raw suffix within 10% of the input budget, on whole-turn boundaries, not a two-turn cap. The turn reference above applies only to short histories that entirely fit this allowance; at least one turn remains a summary candidate. Transport-only mode uses the 8 MiB ceiling. A turn exceeding the allowance may be summarized whole, never truncated; originals are not deleted.'), config);
    const summaryTokens = field(t('摘要输出预算（Token）', 'Summary output budget (tokens)'), 'number', config); summaryTokens.min = 1024; summaryTokens.max = 32768; summaryTokens.step = 1;
    const summaryTime = field(t('压缩时间预算（秒）', 'Summarization timeout (seconds)'), 'number', config); summaryTime.min = SUMMARY_TIME_RANGE[0] / 1000; summaryTime.max = SUMMARY_TIME_RANGE[1] / 1000; summaryTime.step = 1;
    node('small', t('默认300秒，可配置10–1800秒；同时受单轮超时限制。自动整理给后续回答保留10秒；截断重试共用此时间预算。保存后下一轮生效，不延长正在执行的任务。', 'Default: 300 seconds; configurable from 10–1800 seconds, also bounded by the run timeout. Auto-summarization reserves 10 seconds for the answer; truncation retry shares this deadline. Changes apply next run, never extend an active task.'), config);
    node('small', t('默认 16384，上限仍受单次模型输出预算限制，已保存的自定义值保留。手动整理使用此预算；自动整理先用最多 16384，截断且可提高额度、预算允许时最多重试一次。DeepSeek 摘要调用关闭思考，正常对话的思考配置不变；其他兼容接口不额外发送专有思考参数。摘要不固定字符数、不删除原文，更大预算可能增加费用。', 'Defaults to 16384, capped by the per-call model output budget; saved custom values are preserved. Manual summarization uses this budget; automatic summarization starts at up to 16384 and may retry once after truncation if the ceiling can increase and budget permits. DeepSeek summaries disable thinking without changing normal conversation settings; generic endpoints receive no proprietary thinking fields. No fixed character target or original deletion. Larger budgets may cost more.'), config);
    node('small', t('旧历史未覆盖，或完整请求达到输入／请求体预算的 80% 时，在新任务首次请求前尝试整理。每次最多整理一段，计入本轮调用和时间预算；不整理在途工具轨迹。连续三轮失败暂停自动整理，原文保留；百分比不是实际模型窗口。', 'Before a new task’s first request, summarize uncovered history or when the complete request reaches 80% of the input/transport budget. At most one prefix, within the same call/time budget; never compacts live tools. Three failed operations pause automatic summarization; originals remain. This is not the actual model window.'), config);
    // Group the existing controls without rebuilding them or losing their handlers.
    const compressionIndex = Array.from(config.children).indexOf(compression);
    for (const child of Array.from(config.children).slice(compressionIndex + 1)) compression.append(child);
    const actions = node('div', '', config); actions.className = 'gd-muyu-settings-actions';
    const save = button(t('保存上下文设置', 'Save context settings'), actions);
    save.onclick = () => act(() => feedback.run(() => controller.saveContextConfig({ inputTokens: autoBudget.checked ? null : Number(tokens.value), recentTurns: Number(turns.value), autoSummary: auto.checked, historyAuthorization: historyPolicy.value, summaryTokens: Number(summaryTokens.value), summaryTimeMs: Number(summaryTime.value) * 1000 }), () => feedback.validateNumbers()));
    const reset = button(t('恢复默认上下文预算并保存', 'Restore and save default context budget'), actions);
    const feedback = createFormFeedback({ doc, parent: actions, fields: [historyPolicy, autoBudget, tokens, auto, turns, summaryTokens, summaryTime], buttons: [save, reset], retryButton: save, lang, savedText: t('设置已更新，下次任务生效。', 'Settings updated; applies to the next task.') });
    bindAutoSave([historyPolicy, autoBudget, tokens, auto, turns, summaryTokens, summaryTime], save, lang, () => feedback.dirty);
    const fill = c => { historyPolicy.value = c.historyAuthorization ?? CONTEXT_DEFAULTS.historyAuthorization; autoBudget.checked = c.inputTokens === null; tokens.value = String(c.inputTokens ?? CONTEXT_DEFAULTS.inputTokens); turns.value = String(c.recentTurns); summaryTokens.value = String(c.summaryTokens ?? CONTEXT_DEFAULTS.summaryTokens); summaryTime.value = String((c.summaryTimeMs ?? CONTEXT_DEFAULTS.summaryTimeMs) / 1000); auto.checked = c.autoSummary; };
    reset.onclick = () => act(() => feedback.run(async () => { const next = { ...CONTEXT_DEFAULTS, historyAuthorization: savedHistoryPolicy }; await controller.saveContextConfig(next); fill(next); configKey = ''; }));
    const details = node('details', '', parent); details.className = 'gd-muyu-context'; node('summary', t('上下文', 'Context'), details);
    details.open = true;
    const counts = node('p', '', details), coverage = node('p', '', details), usage = node('p', '', details);
    const breakerNote = node('small', '', details), retryAuto = button(t('重新允许自动整理', 'Resume automatic summarization'), details);
    retryAuto.onclick = () => act(() => controller.resetAutoCompaction());
    coverage.setAttribute('aria-live', 'polite');
    const recovery = node('div', '', details), recoveryNote = node('small', '', recovery), source = node('select', '', recovery), grant = button(t('允许所选历史资料', 'Allow selected history source'), recovery);
    grant.onclick = () => act(() => controller.grantHistoryPermission(source.value));
    const omit = field(t('本次不携带旧历史（不撤销工具资料授权）', 'Omit history this send (does not revoke tool access)'), 'checkbox', details);
    omit.onchange = () => act(() => controller.setOmitHistory(omit.checked));
    const preview = node('details', '', details); node('summary', t('查看历史摘要', 'View history summary'), preview); const summary = node('p', '', preview);
    const compact = button(t('立即整理历史', 'Summarize history now'), details), clear = button(t('清除摘要', 'Clear summary'), details), confirm = button(t('确认调用模型整理', 'Confirm model summarization'), details), cancel = button(t('取消整理', 'Cancel summarization'), details);
    const scopeNote = node('small', '', details);
    scopeNote.textContent = t('已切换酒馆聊天：请回到此会话原聊天整理，或发送新消息后再整理。不会为不匹配的聊天调用模型。', 'ST chat changed: return to this conversation’s original chat to summarize, or send a new message first. No model call is made for a mismatched chat.');
    node('small', t('整理会将本会话较早的问答发送到当前模型；只生成参考摘要，不删除原文。手动整理最多一次调用，遵守配置的压缩与单轮时间预算，不恢复工具或权限。', 'Summarizing sends older conversation turns to the current model. It creates a reference summary without deleting originals. Manual operation uses at most one call within configured summarization/run deadlines, never restores tools or permissions.'), details);
    confirm.hidden = cancel.hidden = true;
    compact.onclick = () => { confirm.hidden = cancel.hidden = false; };
    cancel.onclick = () => { confirm.hidden = cancel.hidden = true; };
    confirm.onclick = () => { confirm.hidden = cancel.hidden = true; return act(() => controller.compactHistory()); };
    clear.onclick = () => act(() => controller.clearContextSummary());
    let configKey = '', view = null, savedHistoryPolicy = CONTEXT_DEFAULTS.historyAuthorization;
    return { render(s) {
        const c = s.contextConfig || CONTEXT_DEFAULTS, key = JSON.stringify(c), ctx = s.context || {};
        savedHistoryPolicy = c.historyAuthorization ?? CONTEXT_DEFAULTS.historyAuthorization;
        if (key !== configKey && !feedback.dirty && !feedback.busy) { fill(c); feedback.rebase(); configKey = key; }
        save.disabled = !!s.savingContextConfig || s.resetting;
        breakerNote.hidden = retryAuto.hidden = !s.autoCompaction?.blocked;
        breakerNote.textContent = t('自动整理连续失败三轮，已暂停重复调用。原文与旧摘要保留；可手动整理、调整预算，或明确重新允许自动整理。', 'Automatic summarization failed in three consecutive operations and is paused. Originals and the existing summary remain. Summarize manually, adjust budgets or explicitly resume.');
        retryAuto.disabled = s.busy || s.resetting || s.readOnly;
        reset.disabled = save.disabled;
        feedback.update(s.savingContextConfig || s.resetting);
        tokens.disabled = autoBudget.checked || feedback.busy || !!s.savingContextConfig || !!s.resetting;
        if (view !== s.viewToken || s.busy || s.resetting || s.switchedChat) { confirm.hidden = cancel.hidden = true; view = s.viewToken; }
        compact.disabled = clear.disabled = !s.history?.sessionId || s.readOnly || s.busy || s.resetting;
        compact.disabled ||= !s.enabled || s.switchedChat; clear.disabled ||= !ctx.summary;
        scopeNote.hidden = !s.switchedChat;
        omit.disabled = s.readOnly || s.busy || s.resetting; omit.checked = !!ctx.omitHistory;
        counts.textContent = `${t('计划携带完整问答', 'Planned complete turns')}: ${ctx.turns || 0} · ${t('未覆盖消息', 'Uncovered messages')}: ${ctx.omitted || 0}\n${t('历史部分估算', 'History estimate')}: ${ctx.estimatedTokens || 0} tokens · ${t('摘要', 'Summary')}: ${ctx.summaryStale ? t('来源变化，不使用', 'Stale; not used') : ctx.summaryUsed ? t('使用中', 'In use') : t('未使用', 'Not used')}`;
        if (ctx.omitted > 0) counts.textContent += `\n${t('部分原文未纳入计划；摘要不保证包含每个细节，需要时核对原文。', 'Some original history is not planned; a summary may omit details. Check the original when needed.')}`;
        const covered = ctx.coverage;
        coverage.textContent = covered ? `${t('历史覆盖计划（消息数，非摘要质量保证）', 'History coverage plan (message counts, not a summary quality guarantee)')}: ${covered.total}\n${t('摘要覆盖原文／携带原文／窗口未覆盖／授权或主动排除', 'Summarized originals / raw messages / outside window / excluded by permission or choice')}: ${covered.summarized}/${covered.raw}/${covered.omitted}/${covered.excluded}` : '';
        if (covered?.state === 'blocked') coverage.textContent += t('\n未摘要原文无法完整携带：将尝试整理（若已开启且预算允许），仍放不下则停止。可增加预算、手动整理或明确不携带历史。', '\nThe full unsummarized tail cannot fit: summarization may be attempted if enabled and budgeted; otherwise execution stops. Increase the budget, summarize manually or explicitly omit history.');
        if (covered?.state === 'complete' && covered.summarized > 0) coverage.textContent += t('\n摘要之后的原文连续携带；不代表摘要保留了全部细节。', '\nAll originals after the summary are carried contiguously; this does not guarantee all details survived summarization.');
        const missing = (s.history?.missingPermissions || []).filter(kind => !kind.startsWith('source:providerExecution') && !kind.startsWith('source:scriptExecution') && !kind.startsWith('source:agentExecution') && !kind.startsWith('source:npcExecution') && !kind.startsWith('source:profileExecution') && !kind.startsWith('source:memoryExecution'));
        recovery.hidden = !missing.length || s.readOnly;
        recoveryNote.textContent = t('历史所需资料授权已到期；不会自动省略对话。可在输入框旁允许携带已有对话（不授予新读取权限），或在此授权具体来源。', 'History source access expired; history will not be silently omitted. Allow existing conversation history beside the composer (no fresh read access), or grant a specific source here.');
        const selected = source.value; source.replaceChildren();
        for (const kind of missing) { const option = node('option', kind.startsWith('source:') ? permissionTitle(kind.slice(7)) : kind, source); option.value = kind; }
        source.value = missing.includes(selected) ? selected : missing[0] || '';
        grant.disabled = s.busy || s.resetting || s.interaction?.status === 'pending' || !missing.length;
        summary.textContent = ctx.summary || t('暂无摘要', 'No summary');
        const last = s.runs?.at(-1)?.process, actual = last?.context;
        usage.textContent = actual ? `${t('最近请求估算／预算', 'Last request estimate / budget')}: ${actual.estimatedTokens}/${actual.inputTokenLimit ?? t('自动', 'auto')} tokens · ${actual.requestBytes} B\n${t('实际保留历史消息', 'Retained historical messages')}: ${actual.historicalMessages ?? '?'}\n${t('消息／工具定义／工具结果／思考回传字节（分项存在包含关系）', 'Message / tool definition / tool result / reasoning bytes (overlapping categories)')}: ${actual.messageBytes}/${actual.toolDefinitionBytes}/${actual.toolResultBytes}/${actual.reasoningBytes}\n${t('实际 Token 见本轮开销；估算非实测', 'Actual tokens appear under run usage; estimates are not measurements')}` : '';
        if (actual?.trimmedHistoricalMessages > 0) usage.textContent += `\n${t('发送前因完整请求超出预算，额外移除了历史消息', 'Additional historical messages removed before sending because the full request exceeded budget')}: ${actual.trimmedHistoricalMessages}`;
        if (last?.coverage?.status === 'blocked') usage.textContent += t('\n最近任务因历史连续性保护停止；未向模型发送缺口上下文。', '\nThe last task stopped to preserve history continuity; no gap context was sent to the model.');
        if (last?.coverage?.status === 'fallback') usage.textContent += t('\n最近任务摘要失败，使用原有历史计划继续；原始记录未删除。', '\nThe last task continued with its original history plan after summarization failed; originals were not deleted.');
        const phase = ctx.compacting ? ctx.progress : last?.summaryPhase || ctx.progress;
        if (actual) usage.textContent += `\n${t('指令部分（包含在请求总量内）', 'Instructions (included in request total)')}: ${actual.instructionBytes ?? 0} B`;
        if (phase === 'summarizing') usage.textContent += t('\n正在整理历史…', '\nSummarizing history…');
        if (phase === 'summary_failed') usage.textContent += t('\n摘要尝试失败，原文保留；旧摘要后的原文必须完整携带，否则停止。取消或超时也会停止。', '\nSummary attempt failed; originals preserved. The full tail after an old summary is required, otherwise execution stops. Cancellation or timeout also stops.');
        if (phase === 'summary_failed' && last?.summaryError) usage.textContent += `\n${t('摘要错误代码', 'Summary error code')}: ${last.summaryError}`;
        if (last?.summaryError === 'SUMMARY_NOT_SMALLER') usage.textContent += t('\n摘要连同包装没有比原文更小，未替换已有摘要。', '\nThe framed summary did not reduce the original size; the existing summary was not replaced.');
        if (last?.summaryError === 'SUMMARY_TOO_LARGE') usage.textContent += t('\n摘要超过 512 KiB 安全上限，未保存；原文与已有摘要保留。', '\nThe summary exceeded the 512 KiB safety limit and was not saved; originals and the existing summary remain.');
        if (ctx.usage) usage.textContent += '\n' + formatBudget(ctx.usage, lang);
        if (last?.summaryUsage) usage.textContent += `\n${t('自动摘要调用', 'Auto-summary calls')}: ${last.summaryUsage.calls}\n${t('已报告输入／输出 Token 合计', 'Reported input / output token totals')}: ${last.summaryUsage.inputTokens ?? '?'} / ${last.summaryUsage.outputTokens ?? '?'} (${last.summaryUsage.reports}/${last.summaryUsage.calls} ${t('次有报告；缺失部分未知', 'reported; missing usage unknown')})`;
    } };
}
