import { createToolRegistry } from '../../tools/registry.js';
import { PERMISSION_TOOL, permissionSchema, validatePermission } from '../../permissions/contract.js';

export function createPermissionModule() {
    const registry = createToolRegistry();
    registry.register({ id: PERMISSION_TOOL, version: 1,
        description: 'For ordinary read tools, call the intended tool directly: the host pauses and requests the exact missing source, then resumes that same call after approval. Do not request a read source yourself. Use this control tool ONLY for code permissions: generationBatchExecution requires the exact executionId from generation_batch.prepare; execute pauses for one exact ordered list approval, not separate child approval, with extra-cost models and non-atomic saves; providerExecution requires specific Provider id/revision; scriptExecution requires the exact executionId from scripts.prepare_execution (scripts.execute pauses automatically for consent); npcExecution requires the exact executionId from npc_generation.prepare (execute pauses for business-model costs and trial/append-save consent; never creates/imports character cards). profileExecution requires the exact executionId from profile_generation.prepare (execute pauses for extra model costs and trial/missing-record-save consent); never overwrite existing profiles. memoryExecution requires the exact executionId from memory_generation.prepare (execute pauses for business-model costs and trial/save/pruning consent); read grants do not approve generation. agentExecution requires the exact executionId from agents.prepare_execution (agents.execute pauses automatically for extra model costs and trial/save consent); providerTests allows this task to synthetic-test its drafts with fake contexts, not import them. Send the request ALONE. Provider execution can modify state, use the network or incur costs, and approval applies only to that Provider/version and task. PERMISSION_REQUEST_INVALID is not a user denial. On denial do not repeat or bypass the request.',
        inputSchema: permissionSchema, outputSchema: permissionSchema, scope: 'global', effect: 'read', dataClasses: ['public-knowledge'], confirmation: 'policy', resourceKeys: [], timeoutMs: 1000, retryPolicy: { kind: 'none', maxAttempts: 1 } });
    registry.seal();
    return { registry, handlers: { [PERMISSION_TOOL]: validatePermission }, forgetRun() {}, dispose() {} };
}
