import { copyJson, jsonKey } from '../core/json-contract.js';
export const CHARACTER_TEXT_FIELDS=Object.freeze({description:'角色描述',personality:'性格',scenario:'场景',first_mes:'首条消息',mes_example:'示例对话',system_prompt:'系统提示词',post_history_instructions:'历史后指令',creator_notes:'创作者备注'});
const object=v=>v&&typeof v==='object'&&!Array.isArray(v);
const avatarOk=v=>typeof v==='string'&&v.length<=200&&v.endsWith('.png')&&!/[\\/<>:"|?*\x00-\x1f]/.test(v)&&v!=='.png'&&v!== '..png';
export function createCharacterCardPort({getTarget,getDirectory,load,save,duplicate,create,remove,exists,getReferences,syncCache,isBusy=()=>false,isEditing=()=>true}) {
    const versions=new Map(),plans=new Map(),deleted=new Map();let directory=null,epoch=0,applying=false;
    function state(target){const actual=getTarget(),rows=getDirectory();if(!actual||actual.userKey!==target?.userKey||!['global','chat'].includes(target.kind))throw Error('TARGET_UNAVAILABLE');if(applying||isBusy())throw Error('CHARACTER_BUSY');
        if(!Array.isArray(rows)||rows.length>2048||rows.some(r=>!object(r)||typeof r.name!=='string'||r.name.length>512||!avatarOk(r.avatar))||new Set(rows.map(r=>r.avatar)).size!==rows.length)throw Error('UNSUPPORTED_CHARACTER');
        return {target:copyJson(actual),rows:rows.filter(r=>deleted.get(r.avatar)!==r).map(r=>({name:r.name,avatar:r.avatar}))};}
    const nameOk=name=>typeof name==='string'&&name.length>0&&name.length<=80&&name===name.trim()&&!/[\\/<>:"|?*\x00-\x1f\x7f]/.test(name)&&!/^\.+$/.test(name)&&!name.endsWith('.')&&!/^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(?:\.|$)/i.test(name);
    const normalized=name=>name.normalize('NFKC').trim().toLowerCase();
    function references(avatar){const result=getReferences?.(avatar);if(!object(result)||!Number.isSafeInteger(result.known)||result.known<0)throw Error('CHARACTER_REFERENCES_UNAVAILABLE');if(result.known)throw Error('CHARACTER_REFERENCED');return {known:0,unloadedReferences:'unknown'};}
    function directoryRevision(s){const key=JSON.stringify(s);if(directory?.key!==key)directory={key,revision:crypto.randomUUID()};return directory.revision;}
    function fields(raw){const data=object(raw.data)?raw.data:raw,result={};for(const [field,label]of Object.entries(CHARACTER_TEXT_FIELDS)){const value=data[field]??raw[field];if(value===undefined)continue;if(typeof value!=='string'||value.length>131072)throw Error('UNSUPPORTED_CHARACTER');result[field]={label,value};}return result;}
    async function capture(target,selector){const s=state(target),m=/^card:(0|[1-9]\d{0,3})$/.exec(selector),index=m?Number(m[1]):-1,ticketEpoch=epoch;
        if(index<0||index>=s.rows.length)throw Error('INVALID_CHARACTER_CARD');const identity=s.rows[index];
        const raw=await load(identity.avatar);if(ticketEpoch!==epoch||JSON.stringify(state(target))!==JSON.stringify(s))throw Error('STALE_CHARACTER_CARD');
        if(!object(raw)||raw.shallow||raw.avatar!==identity.avatar||typeof raw.name!=='string')throw Error('UNSUPPORTED_CHARACTER');
        const serialized=typeof raw.json_data==='string'?raw.json_data:JSON.stringify(raw);if(serialized.length>1048576)throw Error('CHARACTER_TOO_LARGE');
        const persisted=JSON.parse(serialized);if(!object(persisted))throw Error('UNSUPPORTED_CHARACTER');
        const key=JSON.stringify([s,JSON.parse(serialized)]),old=versions.get(selector),revision=old?.key===key?old.revision:crypto.randomUUID();
        const result={s,identity,raw,persisted,key,revision};if(versions.size>=128&&!versions.has(selector))versions.delete(versions.keys().next().value);versions.set(selector,result);return result;}
    function page(text,revision,offset){if(text.length>131072)throw Error('CHARACTER_TOO_LARGE');if(!Number.isInteger(offset)||offset<0||offset>text.length||offset&&/[\uDC00-\uDFFF]/.test(text[offset]))throw Error('INVALID_CHARACTER_CARD');let end=Math.min(text.length,offset+6000);if(end<text.length&&/[\uD800-\uDBFF]/.test(text[end-1]))end--;return{text:text.slice(offset,end),revision,nextOffset:end<text.length?end:-1};}
    return Object.freeze({
        list(target,offset=0){const s=state(target);if(!Number.isInteger(offset)||offset<0||offset>2048)throw Error('INVALID_CHARACTER_CARD');return {revision:directoryRevision(s),cards:s.rows.slice(offset,offset+20).map((r,i)=>({name:r.name,selector:'card:'+(offset+i)})),nextOffset:offset+20<s.rows.length?offset+20:-1};},
        async read(target,selector,revision,offset=0){const root=directoryRevision(state(target)),c=await capture(target,selector);if(revision!==c.revision&&!(offset===0&&revision===root))throw Error('STALE_CHARACTER_CARD');
            const data=object(c.raw.data)?c.raw.data:c.raw,metadata={};for(const field of ['creator','character_version','tags','alternate_greetings'])if(Object.hasOwn(data,field)){
                const value=data[field];if(['tags','alternate_greetings'].includes(field)?!Array.isArray(value)||value.length>256||value.some(v=>typeof v!=='string'||v.length>12000):typeof value!=='string'||value.length>12000)throw Error('UNSUPPORTED_CHARACTER');metadata[field]=value;
            }
            const result={name:c.raw.name,fields:fields(c.raw),metadata,worldBook:typeof data.extensions?.world==='string'?data.extensions.world:null,untrusted:true,scope:'shared-character-card',projection:'text fields and whitelisted metadata; no arbitrary extensions, json_data, chats or editor drafts',persistence:'server-observation-not-save-confirmation'};
            return page(JSON.stringify(result),c.revision,offset);},
        async preview(target,args){if(!['update','copy','create','rename','delete'].includes(args.operation))throw Error('INVALID_CHARACTER_CARD');const creating=args.operation==='create',s=state(target);
            const c=creating?{s,identity:null,raw:{name:args.changes?.name},revision:directoryRevision(s)}:await capture(target,args.selector);if(c.revision!==args.revision||creating&&args.selector!=='')throw Error('STALE_CHARACTER_CARD');if(!creating&&isEditing(c.identity.avatar))throw Error('CHARACTER_EDITOR_OPEN');
            const changes=copyJson(args.changes);if(!object(changes)||['copy','delete'].includes(args.operation)&&Object.keys(changes).length||args.operation==='update'&&(!Object.keys(changes).length||Object.entries(changes).some(([k,v])=>!Object.hasOwn(CHARACTER_TEXT_FIELDS,k)||typeof v!=='string'||v.length>12000)))throw Error('INVALID_CHARACTER_CARD');
            if(['create','rename'].includes(args.operation)&&(!nameOk(changes.name)||s.rows.some(r=>normalized(r.name)===normalized(changes.name)&&r.avatar!==c.identity?.avatar)))throw Error('INVALID_CHARACTER_NAME');
            if(args.operation==='rename'&&Object.keys(changes).some(k=>k!=='name')||creating&&Object.entries(changes).some(([k,v])=>k!=='name'&&(!Object.hasOwn(CHARACTER_TEXT_FIELDS,k)||typeof v!=='string'||v.length>12000)))throw Error('INVALID_CHARACTER_CARD');
            if(args.operation==='delete')references(c.identity.avatar);
            const current=fields(c.raw);let before={},after={};
            if(['copy','delete'].includes(args.operation)){if(typeof c.raw.json_data!=='string')throw Error('UNSUPPORTED_CHARACTER');before=args.operation==='delete'?copyJson(c.persisted):null;after=args.operation==='delete'?null:copyJson(c.persisted);}
            else if(creating){before=null;after={name:changes.name,...Object.fromEntries(Object.keys(CHARACTER_TEXT_FIELDS).map(k=>[k,changes[k]??''])),avatar:'host-default',bindings:'none',filename:'host-assigned-unique'};}
            else if(args.operation==='rename'){before={name:c.raw.name};after={name:changes.name};}
            else for(const [k,v]of Object.entries(changes)){if(!Object.hasOwn(current,k))throw Error('UNSUPPORTED_CHARACTER');before[k]={label:CHARACTER_TEXT_FIELDS[k],value:current[k].value};after[k]={label:CHARACTER_TEXT_FIELDS[k],value:v};}
            if(jsonKey(before)===jsonKey(after))throw Error('EMPTY_CHANGES');
            const content=copyJson({module:'character-card',ticket:'character-card:'+crypto.randomUUID(),target:c.s.target,name:c.raw.name,selector:args.selector,operation:args.operation,before,after,warnings:[
                '修改共享角色卡，影响使用该卡的其他聊天；不会改已有消息。 / Shared character card affects other chats; existing messages unchanged.',
                '复制仅复制角色卡PNG，不复制聊天、标签映射或外部附加世界书绑定；原显示名保留，新文件名由酒馆分配。 / Copy duplicates card PNG only, not chats, tag mappings or auxiliary bindings; keeps display name with a host-assigned filename.',
                '不切换聊天、不执行宏、不调用生成或强制刷新编辑器。保存未知不重试／回滚。手动刷新酒馆目录／编辑器后核对。 / No chat switching, macros, generation or editor reload. No retry/rollback on unknown save; refresh UI manually.',
                ...(args.operation==='rename'?['只修改显示名，保留文件名、聊天目录、标签及绑定；不改已有消息中的名字。 / Display name only; filename, chats, tags and bindings retained; past messages unchanged.']:[]),
                ...(creating?['创建使用默认头像，不导入资源或激活／选择角色。 / Creates with default avatar; no imports, activation or selection.']:[]),
                ...(args.operation==='delete'?['永久删除角色PNG，保留聊天文件但入口可能失联；不清理标签／绑定。已知引用阻止删除，未加载及第三方引用未知。请先导出备份；删除后手动刷新酒馆。 / Permanently deletes card PNG, keeps chat files which may become inaccessible. No tag/binding cleanup. Known references block deletion; unloaded/third-party references unknown. Export backup first; refresh ST manually.']:[])
            ]});if(new TextEncoder().encode(JSON.stringify(content)).length>24000)throw Error('CHARACTER_DRAFT_TOO_LARGE');if(plans.size>=64)throw Error('CHARACTER_PLAN_CAPACITY');
            plans.set(content.ticket,{content:copyJson(content),c,changes});return content;},
        assertFresh(content){const p=plans.get(content?.ticket);state(content?.target);if(!p||jsonKey(content)!==jsonKey(p.content)||content.operation!=='create'&&versions.get(content.selector)?.key!==p.c.key||JSON.stringify(state(content.target))!==JSON.stringify(p.c.s))throw Error('STALE_CHARACTER_CARD');if(p.c.identity&&isEditing(p.c.identity.avatar))throw Error('CHARACTER_EDITOR_OPEN');if(content.operation==='delete')references(p.c.identity.avatar);return p;},
        release:content=>plans.delete(content?.ticket),clear(){plans.clear();versions.clear();directory=null;epoch++;},
        async apply(content){const p=this.assertFresh(content);if(content.operation!=='create'){const fresh=await capture(content.target,content.selector);if(fresh.key!==p.c.key)throw Error('STALE_CHARACTER_CARD');}this.assertFresh(content);if(['update','rename'].includes(content.operation)&&typeof save!=='function'||content.operation==='copy'&&typeof duplicate!=='function'||content.operation==='create'&&typeof create!=='function'||content.operation==='delete'&&(typeof remove!=='function'||typeof exists!=='function'))throw Error('WRITE_UNAVAILABLE');applying=true;const applyEpoch=epoch;
            try{if(content.operation==='create'){const values={name:p.changes.name,...Object.fromEntries(Object.keys(CHARACTER_TEXT_FIELDS).map(k=>[k,p.changes[k]??'']))},avatar=await create(values);if(!avatarOk(avatar)||p.c.s.rows.some(r=>r.avatar===avatar))return {status:'outcome_unknown',resourceSave:'unknown'};const result=await load(avatar),observedFields=fields(result);if(applyEpoch!==epoch||jsonKey(getTarget())!==jsonKey(content.target)||result?.avatar!==avatar||result.name!==values.name||Object.keys(CHARACTER_TEXT_FIELDS).some(k=>observedFields[k]?.value!==values[k]))return {status:'outcome_unknown',resourceSave:'unconfirmed'};await syncCache?.(avatar,result,true);return {status:'applied_unconfirmed',resourceSave:'unconfirmed'};}
                if(content.operation==='delete'){await remove(p.c.identity.avatar);if(await exists(p.c.identity.avatar)||applyEpoch!==epoch||jsonKey(getTarget())!==jsonKey(content.target))return {status:'outcome_unknown',resourceSave:'unknown'};references(p.c.identity.avatar);deleted.set(p.c.identity.avatar,getDirectory().find(r=>r.avatar===p.c.identity.avatar));return {status:'applied_unconfirmed',resourceSave:'unconfirmed'};}
                if(content.operation==='copy'){const avatar=await duplicate(p.c.identity.avatar);if(!avatarOk(avatar)||p.c.s.rows.some(r=>r.avatar===avatar))return {status:'outcome_unknown',resourceSave:'unknown'};const result=await load(avatar);if(applyEpoch!==epoch||jsonKey(getTarget())!==jsonKey(content.target)||!object(result)||result.avatar!==avatar||typeof result.json_data!=='string'||jsonKey(JSON.parse(result.json_data))!==jsonKey(p.c.persisted))return {status:'outcome_unknown',resourceSave:'unknown'};await syncCache?.(avatar,result,true);return {status:'applied_unconfirmed',resourceSave:'unconfirmed'};}
                await save(p.c.identity.avatar,p.changes);const observed=await load(p.c.identity.avatar),observedFields=fields(observed);
                if(applyEpoch!==epoch||jsonKey(getTarget())!==jsonKey(content.target)||observed?.avatar!==p.c.identity.avatar||Object.entries(p.changes).some(([k,v])=>k==='name'?observed.name!==v||observed.data?.name!==v:observedFields[k]?.value!==v))return {status:'outcome_unknown',resourceSave:'unconfirmed'};
                await syncCache?.(p.c.identity.avatar,observed,false);return {status:'applied_unconfirmed',resourceSave:'unconfirmed'};
            }catch{return {status:'outcome_unknown',resourceSave:'unknown'};}finally{applying=false;plans.delete(content.ticket);versions.delete(content.selector);directory=null;}}
    });
}
