import test from 'node:test';
import assert from 'node:assert/strict';
import {createProfileSystem} from '../../systems/profile-system.js';
import {createNpcSystem} from '../../systems/npc-system.js';
import {createProfileEditorPort} from '../../muyu/host/profile-editor.js';
import {createNpcEditorPort} from '../../muyu/host/npc-editor.js';
import {createProfileEditorModule} from '../../muyu/modules/profile-editor/index.js';
import {createNpcEditorModule} from '../../muyu/modules/npc-editor/index.js';
import {djb2Hash,hashChar} from '../../utils/string-utils.js';
import {actionReceipt,receiptText,receiptSources,validateReceipt} from '../../muyu/actions/receipts.js';
import {renderProfileEditor} from '../../muyu/ui/profile-editor-view.js';
import {renderNpcEditor} from '../../muyu/ui/npc-editor-view.js';
function fixture(kind,initial={},save=async()=>{}){
 const target={kind:'chat',chatKey:'A'},metadata=structuredClone(initial),settings={npcMaxCount:10,profileEnabled:false,npcEnabled:false};let current=target,meta=metadata,busy=false,saves=0,chars=[{avatar:'a.png',name:'Alice',description:'PRIVATE_CARD',personality:'calm',scenario:'town'},{avatar:'b.png',name:'Bob',description:'other'}];
 const system=kind==='profile'?createProfileSystem({settings,EXT_KEY:'gd',getCharacters:()=>chars,getChatMetadata:()=>meta,djb2Hash,hashChar,saveChatConditional:()=>{throw Error('wrong saver');}}):createNpcSystem({settings,EXT_KEY:'gd',getCharacters:()=>chars,getChatMetadata:()=>meta,saveChatConditional:()=>{throw Error('wrong saver');},log(){}});
 const deps={getTarget:()=>current,getMetadata:()=>meta,extensionKey:'gd',saveChatConfirmed:async()=>{saves++;await save();},isBusy:()=>busy};
 const port=kind==='profile'?createProfileEditorPort({...deps,getCharacters:()=>chars,getCreationContext:system.inspectManualCreation}):createNpcEditorPort({...deps,system});
 const args=()=>kind==='profile'?port.createTargets(target).items[0]:{revision:port.createRead(target).revision};
 const draft=(changes=kind==='profile'?{summary:'PRIVATE_PROFILE'}:{name:'New NPC',description:'PRIVATE_NPC'})=>port.createPreview(target,{...args(),changes});
 return{kind,target,metadata,settings,port,system,args,draft,get saves(){return saves;},get chars(){return chars;},setChars:v=>chars=v,setMeta:v=>meta=v,setTarget:v=>current=v,setBusy:v=>busy=v};
}
for(const kind of ['profile','npc'])for(const initial of [{},{gd:{}}])test('Pure '+kind+' preview initializes only after approval '+JSON.stringify(initial),async()=>{
 const f=fixture(kind,initial),before=structuredClone(f.metadata),d=f.draft();assert.deepEqual(f.metadata,before);assert.equal(f.saves,0);assert.equal(d.before,null);assert.equal(d.operation,'create');assert.equal((await f.port.apply(d)).status,'applied_confirmed');assert.equal(f.saves,1);assert.equal(f.settings.profileEnabled,false);assert.equal(f.settings.npcEnabled,false);await assert.rejects(f.port.apply(d),/STALE/);
});
test('Profile fields use real character hash, preserve archive and schema metadata',async()=>{
 const f=fixture('profile',{gd:{archivedProfiles:{'a.png':{profile:{summary:'ARCHIVE'}}},characterProfiles:{'b.png':{profile:{summary:'Bob'}}},profileVersion:1}}),before=structuredClone(f.metadata),d=f.draft({summary:' summary ',tags:[' tag '],motivation:'goal',relationships:'friend'});
 assert.equal(d.after.hash,hashChar('PRIVATE_CARD','calm','town'));assert.equal(d.after.state,'ready');assert.equal(d.after.manualEdited,true);assert.deepEqual(d.after.profile,{summary:'summary',tags:['tag'],motivation:'goal',relationships:'friend'});await f.port.apply(d);
 assert.deepEqual(f.metadata.gd.archivedProfiles,before.gd.archivedProfiles);assert.deepEqual(f.metadata.gd.characterProfiles['b.png'],before.gd.characterProfiles['b.png']);assert.equal(f.metadata.gd.profileVersion,1);assert.equal(Object.hasOwn(f.metadata.gd,'profileSchemaHash'),false);
});
test('Profile pure business inspection does not initialize or emit card bodies',()=>{const f=fixture('profile'),snapshot=f.system.inspectManualCreation();assert.deepEqual(f.metadata,{});assert.doesNotMatch(JSON.stringify(snapshot),/PRIVATE_CARD|calm|town/);assert.ok(snapshot.schemaHash);});
for(const state of ['ready','failed','pending',null])test('No overwrite of existing profile state '+state,()=>{const f=fixture('profile',{gd:{characterProfiles:{'a.png':state===null?null:{state}}}});assert.equal(f.port.createTargets(f.target).items[0].canCreate,false);assert.throws(()=>f.draft(),/ALREADY_EXISTS/);assert.equal(f.saves,0);});
test('Shared stale Schema refuses creation, without stamping existing profiles',()=>{const f=fixture('profile',{gd:{characterProfiles:{'b.png':{profile:{summary:'old'}}},profileSchemaHash:'outdated'}}),before=structuredClone(f.metadata);assert.throws(()=>f.draft(),/SCHEMA_STALE/);assert.deepEqual(f.metadata,before);});
test('NPC shape is not imported and preserves existing identities',async()=>{const f=fixture('npc',{gd:{npcs:[{name:'Existing',description:'old',importId:'id',imported:true,createdAt:1}],other:3}}),old=f.metadata.gd.npcs[0],d=f.draft({name:' New NPC ',description:' description ',first_mes:' hello '});assert.equal(d.after.imported,false);assert.equal(d.after.importedAvatar,null);assert.equal(d.after.first_mes,'hello');assert.ok(d.after.createdAt>0);await f.port.apply(d);assert.equal(f.metadata.gd.npcs[0],old);assert.equal(f.metadata.gd.other,3);assert.equal(f.metadata.gd.npcs[1].importId,undefined);});
for(const name of ['Alice',' alice ','BOB','Existing',' existing '])test('NPC name collision rejects '+name,()=>{const f=fixture('npc',{gd:{npcs:[{name:'Existing'}]}});assert.throws(()=>f.draft({name,description:'new'}),/COLLISION/);assert.equal(f.saves,0);});
test('NPC capacity does not prune or enable',()=>{const f=fixture('npc',{gd:{npcs:[{name:'Existing'}]}});f.settings.npcMaxCount=1;assert.equal(JSON.parse(f.port.createRead(f.target).text).canCreate,false);assert.throws(()=>f.draft(),/CAPACITY/);assert.equal(f.metadata.gd.npcs.length,1);assert.equal(f.settings.npcEnabled,false);});
for(const kind of ['profile','npc'])for(const [label,mutate] of [
 ['chat',f=>f.setTarget({kind:'chat',chatKey:'B'})],['metadata',f=>f.setMeta(structuredClone(f.metadata))],['root',f=>f.metadata.gd={...f.metadata.gd}],['busy',f=>f.setBusy(true)],['role name',f=>f.chars[0].name='Renamed'],
])test(kind+' stale creation approval '+label,async()=>{const f=fixture(kind,{gd:{}}),d=f.draft();mutate(f);await assert.rejects(f.port.apply(d));assert.equal(f.saves,0);});
for(const [label,mutate]of [['new profile',f=>f.metadata.gd.characterProfiles['a.png']={state:'ready'}],['body hash',f=>f.chars[0].description='changed'],['Schema',f=>f.settings.profileJsonSchema='{"type":"object"}'],['store identity',f=>f.metadata.gd.characterProfiles={}],['schema metadata',f=>f.metadata.gd.profileSchemaHash='changed']])test('Profile creation invalidates '+label,async()=>{const f=fixture('profile',{gd:{characterProfiles:{}}}),d=f.draft();mutate(f);await assert.rejects(f.port.apply(d));assert.equal(f.saves,0);});
for(const [label,mutate]of [['new NPC',f=>f.metadata.gd.npcs.push({name:'Other'})],['entry replace',f=>f.metadata.gd.npcs[0]={...f.metadata.gd.npcs[0]}],['name update',f=>f.metadata.gd.npcs[0].name='Renamed'],['capacity',f=>f.settings.npcMaxCount=1],['characters',f=>f.chars.push({avatar:'c.png',name:'New NPC'})]])test('NPC creation invalidates '+label,async()=>{const f=fixture('npc',{gd:{npcs:[{name:'Existing'}]}}),d=f.draft();mutate(f);await assert.rejects(f.port.apply(d));assert.equal(f.saves,0);});
test('Unrelated profile body and archive update survive creation',async()=>{const f=fixture('profile',{gd:{characterProfiles:{'b.png':{profile:{summary:'old'}}},archivedProfiles:{}}}),d=f.draft();f.metadata.gd.characterProfiles['b.png'].profile.summary='concurrent';f.metadata.gd.archivedProfiles['a.png']={profile:{summary:'concurrent archive'}};await f.port.apply(d);assert.equal(f.metadata.gd.characterProfiles['b.png'].profile.summary,'concurrent');assert.equal(f.metadata.gd.archivedProfiles['a.png'].profile.summary,'concurrent archive');});
test('Unrelated NPC body edit survives creation and shares future business mutations',async()=>{const f=fixture('npc',{gd:{npcs:[{name:'Existing',description:'old'}]}}),d=f.draft();f.metadata.gd.npcs[0].description='concurrent';await f.port.apply(d);assert.equal(f.metadata.gd.npcs[0].description,'concurrent');const row=f.port.list(f.target).items[1];const edit=f.port.preview(f.target,{...row,operation:'update',changes:{description:'edited'}});await f.port.apply(edit);assert.equal(f.metadata.gd.npcs[1].description,'edited');});
for(const kind of ['profile','npc'])test(kind+' rejected save leaves own and concurrent data, no replay',async()=>{let f;f=fixture(kind,{},async()=>{f.metadata.gd.other='concurrent';throw Error('offline');});const d=f.draft(),r=await f.port.apply(d);assert.equal(r.status,'outcome_unknown');assert.equal(r.chatSave,'unknown');assert.equal(f.metadata.gd.other,'concurrent');assert.equal(f.saves,1);await assert.rejects(f.port.apply(d));assert.equal(f.saves,1);});
for(const kind of ['profile','npc'])test(kind+' successful save with own data change returns partial',async()=>{let f;f=fixture(kind,{},async()=>{if(kind==='profile')f.metadata.gd.characterProfiles['a.png'].profile.summary='later';else f.metadata.gd.npcs[0].description='later';});assert.equal((await f.port.apply(f.draft())).status,'partial');});
for(const kind of ['profile','npc'])for(const changes of [{},null,[],{summary:'x',hash:'invented'},{name:'X',description:'x',imported:true},JSON.parse('{"__proto__":true}')])test(kind+' invalid creation input '+JSON.stringify(changes),()=>{const f=fixture(kind);assert.throws(()=>f.draft(changes));assert.deepEqual(f.metadata,{});});
test('Profile required summary and tag bounds reject',()=>{const f=fixture('profile');for(const changes of [{summary:' '},{summary:'x',tags:['']},{summary:'x',tags:Array(65).fill('x')},{summary:'x'.repeat(12001)},{summary:'x',motivation:3}])assert.throws(()=>f.draft(changes));});
test('Profile creation respects editor store capacity without dropping records',()=>{const store=Object.fromEntries(Array.from({length:512},(_,i)=>['old'+i,{state:'ready'}])),f=fixture('profile',{gd:{characterProfiles:store}});assert.equal(f.port.createTargets(f.target).items[0].canCreate,false);assert.throws(()=>f.draft(),/CAPACITY/);assert.equal(Object.keys(f.metadata.gd.characterProfiles).length,512);});
test('NPC larger runtime capacity retains independent editor bound',()=>{const f=fixture('npc');f.settings.npcMaxCount=1000;const info=JSON.parse(f.port.createRead(f.target).text);assert.equal(info.limit,1000);assert.equal(info.editorLimit,512);assert.equal(info.canCreate,true);assert.equal(f.draft().operation,'create');});
for(const kind of ['profile','npc'])test(kind+' missing confirmed saver cannot initialize data',async()=>{const f=fixture(kind),deps={getTarget:()=>f.target,getMetadata:()=>f.metadata,extensionKey:'gd'},port=kind==='profile'?createProfileEditorPort({...deps,getCreationContext:f.system.inspectManualCreation}):createNpcEditorPort({...deps,system:f.system}),args=kind==='profile'?port.createTargets(f.target).items[0]:port.createRead(f.target),d=port.createPreview(f.target,{...args,changes:kind==='profile'?{summary:'x'}:{name:'X',description:'x'}});await assert.rejects(port.apply(d),/WRITE_UNAVAILABLE/);assert.deepEqual(f.metadata,{});});
for(const mutate of [f=>f.chars[0].avatar='constructor',f=>f.chars[1].avatar=f.chars[0].avatar])test('Profile ambiguous/unsafe role mapping refuses creation',()=>{const f=fixture('profile');mutate(f);assert.throws(()=>f.draft(),/CHARACTERS/);assert.deepEqual(f.metadata,{});});
test('NPC string type/length bounds reject',()=>{const f=fixture('npc');for(const changes of [{name:'',description:'x'},{name:'x',description:' '},{name:'x',description:'x',first_mes:3},{name:'x'.repeat(201),description:'x'},{name:'x',description:'x'.repeat(12001)}])assert.throws(()=>f.draft(changes));});
for(const kind of ['profile','npc'])test(kind+' multibyte diff overflow is not truncated',()=>{const f=fixture(kind);assert.throws(()=>f.draft(kind==='profile'?{summary:'猫'.repeat(9000)}:{name:'X',description:'猫'.repeat(9000)}),/TOO_LARGE/);assert.equal(f.saves,0);});
for(const kind of ['profile','npc'])test(kind+' creation read charges shared budget and clear invalidates plan',async()=>{const f=fixture(kind),m=(kind==='profile'?createProfileEditorModule:createNpcEditorModule)({port:f.port,charge:()=>false});assert.throws(()=>m.handlers['muyu.'+kind+'_editor.'+(kind==='profile'?'create_targets':'create_read')]({offset:0},{target:f.target,runId:'r'}),/BUDGET/);const d=f.draft();f.port.clear();await assert.rejects(f.port.apply(d),/STALE/);assert.equal(f.saves,0);});
for(const kind of ['profile','npc'])test(kind+' v30 receipt contains no content/identity and cannot use old v22/v23',()=>{const f=fixture(kind),content=f.draft(),r=actionReceipt({id:'op',artifactId:'draft',revision:1,status:'applied_confirmed',content,result:{chatSave:'confirmed'}});assert.equal(r.version,30);assert.deepEqual(receiptSources(r),[]);assert.doesNotMatch(JSON.stringify(r),/PRIVATE_|Alice|a.png|New NPC/);assert.match(receiptText(r,'zh'),/历史/);assert.match(receiptText(r,'en'),/Historical/);assert.throws(()=>validateReceipt({...r,version:kind==='profile'?22:23}));});
for(const kind of ['profile','npc'])for(const lang of ['zh','en'])test(kind+' creation card localized, full diff and folded '+lang,()=>{const elements=[],doc={createElement(tag){const e={tag,textContent:'',append(){},setAttribute(){}};elements.push(e);return e;}},f=fixture(kind);(kind==='profile'?renderProfileEditor:renderNpcEditor)({doc,card:doc.createElement('article'),artifact:{id:'a',revision:1,content:f.draft()},state:{},controller:{},act(){},lang});const text=elements.map(e=>e.textContent).join('\n');assert.match(text,lang==='zh'?/新建/:/Create/);assert.match(text,/"before": null/);assert.match(text,/PRIVATE_/);assert.ok(elements.some(e=>e.tag==='details'));});
